

#inhibit_all_warnings!
use_frameworks!


target 'SpecToolsExample' do
    platform :ios, '10.2'
    pod 'SnapKit'
    
    target 'SpecToolsExampleTests' do
        inherit! :search_paths
        
        pod 'SpecTools', :path => '../'
        pod 'Quick'
        pod 'Nimble'
    end
end


target 'TVExample' do
    platform :tvos, '10.2'
    pod 'SnapKit'
    
    target 'TVExampleTests' do
        inherit! :search_paths
        
        pod 'SpecTools', :path => '../'
        pod 'Quick'
        pod 'Nimble'
    end
end

